import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LanguageSwitcher from "@/app/components/LanguageSwitcher"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          style={{
            padding: "12px 16px",
            borderBottom: "1px solid #e0e0e0",
            display: "flex",
            justifyContent: "flex-end",
            backgroundColor: "#f9f9f9",
          }}
        >
          <LanguageSwitcher />
        </header>
        {children}
      </body>
    </html>
  );
}
